## YAML Template.
---
eureka:
    client:
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:1313/eureka/
zuul:
    routes:
        google:
            path: /google/**
            url: https://www.google.com/
        prueba:
            path: /prueba/**
            url: http://localhost:1515/